### PR TITLE
Update Ingress to non-beta version

### PR DESCRIPTION
**Pull request by rjhenry**

### CODE REVIEW

**Comment by jzandbergen** [comment]
Could someone please comment or approve this PR? The chart is using deprecated API's and will soon no longer install.

**Comment by bootc** [comment]
I've got changes that supersede this MR waiting in a branch, I just need some more time to get it all sorted out.

**Comment by anthr76** [comment]
Any chance this can get looked at?

**Comment by stv0g** [comment]
I would also need these changes

**Comment by rjhenry** [comment]
This has been superseded by Chris' efforts on the `develop` branch, specifically 8f28a0c775727c63bb45a95aab46ca5f3a28b6e2 - it's also a better solution than this PR, as it only uses non-beta Ingress on cluster that can handle it, rather than everywhere like this one does.

Closing this PR in favour of the already-existing changes.

**Comment by anthr76** [comment]
That's great. Would it be possible to cut a release so usable can be possible on Kubernetes 1.22?

**Pull request closed without merging**
