### PR TITLE
Add LDAP support for netbox chart

### PR DESCRIPTION
**Pull request by Comradin**
Added a secrets template with the content of the ldap_config.py file and
mounted it into the netbox pod.

The values.yaml got extended for the necessary keys described in the
documentation.

Chart version updated to 1.0.5

Addresses #6 

Signed-off-by: Marcus Franke <marcus.franke@gmail.com>

### CODE REVIEW

**Comment by Comradin** [comment]
The latest two commits were necessary for the setup to make it actually work.

Sorry for the incomplete solution in the first place.

**Comment by bootc** [comment]
Hey, thanks for your contribution! It might take me a few days to get a good look at it and come back with some more feedback, but until then two things jump out at me:

1. It looks like it'll only work with Active Directory, and then only for organisations that use the `sAMAccountName` attribute for login. It would be nice to allow this to be more generic.

2. There's no documentation for the new parameters or how to configure it.

FWIW I personally configure this on one of my installations with a `ConfigMap` and extra volume mounts. My chart values look like this:

```
    image:
      tag: v2.6.12-ldap

    extraVolumeMounts:
    - mountPath: /etc/netbox/config/ldap_config.py
      name: ldap-config
      subPath: ldap_config.py
      readOnly: true

    extraVolumes:
    - name: ldap-config
      configMap:
        name: netbox-ldap
```

Then the `ldap-config` ConfigMap looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-ldap
  namespace: netbox
  labels:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
data:
  ldap_config.py: |
    import os
    import ldap
    from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

    AUTH_LDAP_SERVER_URI = ' '.join([
        'ldap://ldap.example.com',
    ])
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0
    }
    AUTH_LDAP_START_TLS = True
    LDAP_IGNORE_CERT_ERRORS = False
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        'dc=example,dc=com',
        ldap.SCOPE_SUBTREE,
        "(uid=%(user)s)")
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        'dc=example,dc=com',
        ldap.SCOPE_SUBTREE,
        '(objectClass=groupOfNames)')
    AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
    AUTH_LDAP_REQUIRE_GROUP = 'cn=netbox,ou=groups,dc=example,dc=com'
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        'is_active': AUTH_LDAP_REQUIRE_GROUP,
        'is_staff': 'cn=staff,ou=groups,dc=example,dc=com',
        'is_superuser': 'cn=netbox-admins,ou=groups,dc=example,dc=com',
    }
    AUTH_LDAP_FIND_GROUP_PERMS = True
    AUTH_LDAP_CACHE_GROUPS = True
    AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600
    AUTH_LDAP_USER_ATTR_MAP = {
        'first_name': 'givenName',
        'last_name': 'sn',
        'email': 'mail',
    }
```

Also please note that I'm making some significant changes to the chart to accommodate the recent NetBox 2.7 release, so I might be tempted to wait until I've got that in before doing much more work. Just a heads-up.

**Comment by Comradin** [comment]
Hello Chris,

thanks for the reply. We choose to use a Secret instead of the ConfigMap because of the password contained in AUTH_LDAP_BIND_PASSWORD.

Ill look into your points in the next days.

**Comment by Comradin** [comment]
Hi @bootc ,

It took me a while to add the description of the LDAP parameters to the Configuration settings of the README.md file. Writing documentation seems to be harder than I expected.

One interesting thing you may consider for the rewrite of the Chart to be ready for the 2.7.x releases of Netbox, there are special v2.(6|7).x-ldap tagged images for ldap support. We had some struggles to make the original -ldap-less images work with our ldap_config.py file, until we figured out it has to be mounted in the /opt/netbox/netbox/netbox directory.

**Comment by ilhaan** [comment]
Any plans to merge this soon? I would like to get Netbox with LDAP installed soon and this chart seems to be the best option out there. 

Happy to help if this needs some work as well.

**Comment by bootc** [comment]
@ilhaan sorry I missed your comment; I'm hopefully going to work on this soon to integrate the LDAP support more natively into the Helm chart, but in the mean time my suggestion in https://github.com/bootc/netbox-chart/pull/7#issuecomment-582327368 still works—this is how one of my NetBox instances is configured.

Note also that NetBox 2.8 has a new [Remote Authentication](https://github.com/netbox-community/netbox/issues/2328) system which might be preferable (e.g. for use with [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy)). That should be [configurable](https://github.com/bootc/netbox-chart/blob/2.3.0/values.yaml#L178-L185) with the chart today, though I haven't tried it yet.

**Comment by myannou** [comment]
Hello,
Did you have a chance to review this request ?
Will be nice to get this feature included directly in the chart
Thanks

**Comment by bootc** [comment]
Closing in favour of #31.

**Pull request closed without merging**
